version: '3'
services:
  app:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile_local
    image: ${APP_NAME}
    container_name: ${APP_NAME}
    ports:
      - '${PORT}:80'
    volumes:
      - ../dist:/app/dist
      - ../src:/app/src
    environment:
      - DB=${DB}
